### ISSUE TITLE
Feature: Address Management in Coordinate Share window and JSON file

### ISSUE THREAD

**Issue by xGnoSiSx** [Kevin0M16/NMSCoordinates#46]
I think you need to add some convenience features to add or remove a single address from the other windows into the Coordinate Share, in the current open JSON file. Because as you use this actively, you end up with far too many separate files.

As I use this, I can indeed edit the JSON code in a text editor to add things, but some more tools to add, update, merge a JSON file, (and dropping duplicates/ sync comments) in app would be golden.

Great App! Thanks!

**Comment by Kevin0M16** [comment]
Thanks for the suggestion! I will take a look a this and I appreciate the feedback.

**Comment by Kevin0M16** [comment]
Added on v2.2. Thanks for the suggestions.
