### ISSUE TITLE
NMS 4.0

### ISSUE THREAD

**Issue by denali1** [Kevin0M16/NMSCoordinates#48]
NMSCoordinates doesn't seem to support two new NMS 4.0 features:

1) New game modes, such as "Custom" games.
2) NMS 4.0 now has more than five save slots.

**Comment by Kevin0M16** [comment]
Thanks for bringing this up. I haven't played in a while. I can take a look at these.

1. What seems to be the issue with the game modes?
2. Ok. Yes, NMSCoordinates only gets the first 5 saves. I can probably fix it. Do you know what the max save count is?

**Comment by denali1** [comment]
Thanks for responding!

1) The game now supports the following modes: Normal, Relaxed, Creative, Expedition, Custom and Survival.
2) 15 and they can now be renamed.  The save system also has added the ability to tell you where you're at in the save screen (Ex. "On freighter (MS-9 Suzukayase)", "Within <Player Base Name>").

**Comment by Kevin0M16** [comment]
I made some changes to the v2.2 PR I was working on. Would you mind testing this v2.2 beta to see if it works ok?

Thanks.

[NMSCoordinates-v2.2-beta.zip](https://github.com/Kevin0M16/NMSCoordinates/files/9847990/NMSCoordinates-v2.2-beta.zip)

**Comment by denali1** [comment]
I'm sorry I took so long to respond.  GitHub didn't tell me you had replied.

It does now see my custom save which is in slot 13 and is able to load it!  However, when I go to trigger a freighter battle, it tells me that a save slot isn't selected, even though it is selected in the "Save Files" tab.

**Comment by Kevin0M16** [comment]
Thanks for testing. I believe I have fixed the "select save slot" issue.  Try beta 4

https://github.com/Kevin0M16/NMSCoordinates/pull/44#issuecomment-1304092141

**Comment by Kevin0M16** [comment]
Fixed with v2.2
