### ISSUE TITLE
NMS v4.7+ failure

### ISSUE THREAD

**Issue by bignmllc** [Kevin0M16/NMSCoordinates#51]
![nmscoords-failure](https://github.com/Kevin0M16/NMSCoordinates/assets/743568/9f0256af-289f-41d7-9dfe-e589d7b811ea)

As you can see in the attached picture, I am getting an error code when trying to use NMSCoordinates software.  After starting the app, and then selecting the proper slot, it takes a few seconds, and then says (below):

This Version: v2.2 is the latest version
Problem loading json! ERROR [6]save4.hg
** Code 111 **
** Code 3 ** [3, save4.hg]
** Code 111 **

It does this on all my slots, not just this one, so I think there may be some kind of imcompatibility with the new NMS v4.7+?

Just a heads up. Thanks for your hard work.

Best,
Tom Straub
"Tom" in NMS

**Comment by Kevin0M16** [comment]
This issue will be resolved in the upcoming #53 pull request. I need to test a few more save file.
