### ISSUE TITLE
Error code 111

### ISSUE THREAD

**Issue by GamerPi** [Kevin0M16/NMSCoordinates#52]
I am experiencing the same issue with this project as Bignmllc. The tool cannot process the json file and spits out error 111. I am unsure if this is an issue with it reading euclid saves or what because my 2nd slot is in Eissentam and it can read the save with no issues.

**Comment by Kevin0M16** [comment]
This issue is the same as #51 and will be resolved in the upcoming #53 pull request. Closing this issue now as it duplicates #51.
